apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: switchlang-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ujeongoh/switchlang.git
    targetRevision: HEAD
    path: k8s  # manifest folder path
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true      # resource deleted from Git, also delete from K8s
      selfHeal: true   # if manually modified, restore to original state
    syncOptions:
      - CreateNamespace=true